### ISSUE TITLE
Manual installation with Contao 3.5

### ISSUE THREAD

**Issue by dispyfree** [postyou/contao-facebook-connector_basic#2]
Dear Sir or Madam, 

due to the lack of SSH access (so no composer) as well as a SOAP extension for the version of PHP deployed, I have to manually install this extension.  To be specific, I run Contao 3.5.25 on PHP  5.5.21.
First of all, you name Contao 3.6 as well as PHP 5.6 as the minimum requirements (at least in Composer). 
Are those "hard" requirements, implying that I cannot run your module with this configuration?

As for the installation itself (naturally rendered void if hard minimum requirements as stated above are not met): 
I followed the following approaches: 
- extracting the files in the root directory of Contao
- extracting the files to system/modules
- in both cases, update Contao's database in the backend.

With both approaches, Contao does not seem to recognize the module at all.

Thank you for your help!

**Comment by theDyingMountain** [comment]
Hello,

you can run the module with Contao 3.5. The composer.json specifies contao core version >=3.5.
The PHP Version is no "hard" requirement, you can try it with version 5.5.

Did you try running the Contao Autoload Creator and/or disabling the DCA Cache in the backend settings?

**Comment by dispyfree** [comment]
indeed, I did not run the autoload creator. After having included this step, the extension gets installed.
Thank you very much for your help!
