### ISSUE TITLE
Contao 4.4

### ISSUE THREAD

**Issue by tblumrich** [postyou/contao-facebook-connector_basic#3]
Hallo!

Ist es geplant, das Modul auch für Contao 4 zur Verfügung zu stellen?

Danke und schöne Feiertage! :)

**Comment by theDyingMountain** [comment]
Hallo,

ja wir arbeiten gerade daran, das Modul als Contao 4 Bundle zu veröffentlichen.
Ich melde mich wenn es fertig ist :)

**Comment by theDyingMountain** [comment]
Hallo,
das Modul für Contao 4 steht nun unter: [https://github.com/postyou/contao-facebook-connector_basic-bundle](https://github.com/postyou/contao-facebook-connector_basic-bundle) zur Verfügung.
