### ISSUE TITLE
Show full post text

### ISSUE THREAD

**Issue by Metis77** [postyou/contao-facebook-connector_basic#5]
the facebook post text gets split in title and message.
I'd love to have the option to use the "full text".

Like this:
Überschrifttyp*
 Satzzeichen
 Zeichenlänge
 ohne Überschrift (zeigt kompletten Text)

**Comment by theDyingMountain** [comment]
gefixt im letzten Release des [Contao 4 Bundles](https://github.com/postyou/contao-facebook-connector_basic-bundle). In der Version für Contao werden keine neuen Features mehr implementiert.
