### ISSUE TITLE
CE add CSS Class/ID + Template

### ISSUE THREAD

**Issue by Metis77** [postyou/contao-facebook-connector_basic#6]
I need to add a css class in from the content element.

Related to this, have the defautl fields CSS ID/Class and the option to change the used template would be great.

**Comment by theDyingMountain** [comment]
Can you please post your new feature requests in the [Contao 4 Bundle Repository](https://github.com/postyou/contao-facebook-connector_basic-bundle)? This repository for Contao 3 is only maintained with bug fixes, no feature requests.
